/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsignaturasIndexRouteImport } from './routes/asignaturas.index'
import { Route as AsignaturasIdAsignaturaIndexRouteImport } from './routes/asignaturas.$idAsignatura.index'
import { Route as AsignaturasIdAsignaturaEvaluacionesIdEvaluacionRouteImport } from './routes/asignaturas.$idAsignatura.evaluaciones.$idEvaluacion'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsignaturasIndexRoute = AsignaturasIndexRouteImport.update({
  id: '/asignaturas/',
  path: '/asignaturas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsignaturasIdAsignaturaIndexRoute =
  AsignaturasIdAsignaturaIndexRouteImport.update({
    id: '/asignaturas/$idAsignatura/',
    path: '/asignaturas/$idAsignatura/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AsignaturasIdAsignaturaEvaluacionesIdEvaluacionRoute =
  AsignaturasIdAsignaturaEvaluacionesIdEvaluacionRouteImport.update({
    id: '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion',
    path: '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/asignaturas/': typeof AsignaturasIndexRoute
  '/asignaturas/$idAsignatura/': typeof AsignaturasIdAsignaturaIndexRoute
  '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion': typeof AsignaturasIdAsignaturaEvaluacionesIdEvaluacionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/asignaturas': typeof AsignaturasIndexRoute
  '/asignaturas/$idAsignatura': typeof AsignaturasIdAsignaturaIndexRoute
  '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion': typeof AsignaturasIdAsignaturaEvaluacionesIdEvaluacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/asignaturas/': typeof AsignaturasIndexRoute
  '/asignaturas/$idAsignatura/': typeof AsignaturasIdAsignaturaIndexRoute
  '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion': typeof AsignaturasIdAsignaturaEvaluacionesIdEvaluacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/perfil'
    | '/asignaturas/'
    | '/asignaturas/$idAsignatura/'
    | '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/perfil'
    | '/asignaturas'
    | '/asignaturas/$idAsignatura'
    | '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/perfil'
    | '/asignaturas/'
    | '/asignaturas/$idAsignatura/'
    | '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  AsignaturasIndexRoute: typeof AsignaturasIndexRoute
  AsignaturasIdAsignaturaIndexRoute: typeof AsignaturasIdAsignaturaIndexRoute
  AsignaturasIdAsignaturaEvaluacionesIdEvaluacionRoute: typeof AsignaturasIdAsignaturaEvaluacionesIdEvaluacionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asignaturas/': {
      id: '/asignaturas/'
      path: '/asignaturas'
      fullPath: '/asignaturas/'
      preLoaderRoute: typeof AsignaturasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asignaturas/$idAsignatura/': {
      id: '/asignaturas/$idAsignatura/'
      path: '/asignaturas/$idAsignatura'
      fullPath: '/asignaturas/$idAsignatura/'
      preLoaderRoute: typeof AsignaturasIdAsignaturaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion': {
      id: '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion'
      path: '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion'
      fullPath: '/asignaturas/$idAsignatura/evaluaciones/$idEvaluacion'
      preLoaderRoute: typeof AsignaturasIdAsignaturaEvaluacionesIdEvaluacionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  AsignaturasIndexRoute: AsignaturasIndexRoute,
  AsignaturasIdAsignaturaIndexRoute: AsignaturasIdAsignaturaIndexRoute,
  AsignaturasIdAsignaturaEvaluacionesIdEvaluacionRoute:
    AsignaturasIdAsignaturaEvaluacionesIdEvaluacionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
